### ISSUE TITLE
Spotify API now requires OAuth even for /search

### ISSUE THREAD

**Issue by devgeeks** [phonegap/phonegap-app-star-track#26]
This is why searching no longer works...

This is a bit of a deal breaker. I am not sure the value of the app is there if it requires app registration and a user account.

Not sure what the next steps could be.

The iTunes API doesn't support CORS, so developing in the browser is a pain. This app might be dead :/

We'll have to look for other options.

**Comment by filmaj** [comment]
==> #27

**Comment by filmaj** [comment]
#27 resolves this.
